// attr_id.h
#pragma once

#ifndef __DLL_ATTRID_H
#define __DLL_ATTRID_H

enum KPID_PROPERTIES
{
  KPID_NO_PROPERTY = 0,
  
  KPID_HANDLER_ITEM_INDEX = 2,
  KPID_PATH,
  KPID_NAME,
  KPID_EXTENSION,
  KPID_IS_DIR,
  KPID_SIZE,
  KPID_PACK_SIZE,
  KPID_ATTRIB,
  KPID_CTIME,
  KPID_ATIME,
  KPID_MTIME,
  KPID_SOLID,
  KPID_COMMENTED,
  KPID_ENCRYPTED,
  KPID_SPLIT_BEFORE,
  KPID_SPLIT_AFTER,
  KPID_DICTIONARY_SIZE,
  KPID_CRC,
  KPID_TYPE,
  KPID_IS_ANTI,
  KPID_METHOD,
  KPID_HOST_OS,
  KPID_FILE_SYSTEM,
  KPID_USER,
  KPID_GROUP,
  KPID_BLOCK,
  KPID_COMMENT,
  KPID_POSITION,
  KPID_PREFIX,
  KPID_NUM_SUB_DIRS,
  KPID_NUM_SUB_FILES,
  KPID_UNPACK_VER,
  KPID_VOLUME,
  KPID_IS_VOLUME,
  KPID_OFFSET,
  KPID_LINKS,
  KPID_NUM_BLOCKS,
  KPID_NUM_VOLUMES,
  KPID_TIME_TYPE,
  KPID_BIT64,
  KPID_BIG_ENDIAN,
  KPID_CPU,
  KPID_PHY_SIZE,
  KPID_HEADERS_SIZE,
  KPID_CHECKSUM,
  KPID_CHARACTS,
  KPID_VA,

	KPID_VIEWABLE = 0x100, // attr set plugin filter
	KPID_SUSPICIOUS,
	KPID_CONTAINTEXT,
	KPID_ARCHIVE,
	KPID_CONTAINER,
	KPID_PROCESSITEM,
	KPID_ICONID,

	KPID_PROCESS_ALL_STREAMS_IN_ARCHIVE = 0x200,

	KPID_COMMENTS = 0x900,
	KPID_EXIF_MAIN,
	KPID_EXIF_EXIF,
	KPID_EXIF_GPS,
	KPID_EXIF_MAKER_NOTE,
	KPID_EXIF_INTEROP,
	KPID_IPTC,
	KPID_XMP,
	KPID_GEO_TIFF,
	KPID_EXIF_TAG_ORIENTATION,

  KPID_TOTAL_SIZE = 0x1100,
  KPID_FREE_SPACE,
  KPID_CLUSTER_SIZE,
  KPID_VOLUME_NAME,

  KPID_LOCAL_NAME = 0x1200,
  KPID_PROVIDER,

	KPID_FILE_TEMPORARY_ITEM = 0x1300,
	KPID_FILE_TEMPORARY_RESOURCE = 0x1301,
	KPID_FILE_STREAM = 0x1302,
	KPID_CACHE_STREAM = 0x1304,

  KPID_USER_DEFINED = 0x10000
};

#endif // __DLL_ATTRID_H
